### PR TITLE
Place index.md when creating new project

### PR DESCRIPTION
**Pull request by JohnTitor**
### Types of this PR

- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [ ] Test
- [ ] Refactor

### Description

`hibana new <foo>`をしたときに`index.md`を`contents`配下に配置するようにしました

### CODE REVIEW

**Comment by k-nasa** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 4c0ae1a56d1c977a018f4cdde616149305e458fb has been approved by `k-nasa`

**Comment by KoujiroFrau** [comment]
:hourglass: 4c0ae1a56d1c977a018f4cdde616149305e458fb has been merged into the auto branch 2d3332405647c2eea9aa20e5d4a3a6a7a6edd15f

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/student-kyushu/hibana/builds/484595243?utm_source=github_status&utm_medium=notification)

**Pull request merged**
