### PR TITLE
For newcomer, and Koujiro Frau

### PR DESCRIPTION
**Pull request by JohnTitor**
### Types of this PR

- [ ] Bug fix
- [ ] New feature
- [x] Documentation
- [ ] Test
- [ ] Refactor

### Description

神代フラウは天才的なプログラマであり愛すべきあっとチャネラーです
彼女への敬意を表してCONTRIBUTINGに説明を加えましょう

### CODE REVIEW

**Comment by k-nasa** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 100c33815bc2725d5ddcdeec160fe80c9d1228f4 has been approved by `k-nasa`

**Comment by KoujiroFrau** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/student-kyushu/hibana/builds/484691266?utm_source=github_status&utm_medium=notification)

**Pull request merged**
