### PR TITLE
Improve documents

### PR DESCRIPTION
**Pull request by JohnTitor**
### Types of this PR

- [ ] Bug fix
- [ ] New feature
- [x] Documentation
- [ ] Test
- [ ] Refactor

### Description

正しいのは https://www.kyushu.gr.jp だぞ！とお達しがあったので
ただそれだけでは寂しいのでついでにREADMEもちょこっと書きました

r? @k-nasa

### CODE REVIEW

**Comment by k-nasa** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dc36b70a94592c902564fc8c61972993025e7ed3 has been approved by `k-nasa`

**Comment by KoujiroFrau** [comment]
:hourglass: dc36b70a94592c902564fc8c61972993025e7ed3 has been merged into the auto branch 2a7f5659ab9a27dd30fc334ed47dd8ea3d2fec44

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Pull request merged**
