### PR TITLE
docs: Format documents

### PR DESCRIPTION
**Pull request by JohnTitor**
### Types of this PR

- [ ] Bug fix
- [ ] New feature
- [x] Documentation
- [ ] Test
- [ ] Refactor

### Description

lintに怒られたので直しました

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 0afed555f31cd5579509eb6a4ce3c45494d3788a has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 0afed555f31cd5579509eb6a4ce3c45494d3788a has been merged into the auto branch 6dd9123b4b549b7973b831f847e2f944136ee836

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/student-kyushu/hibana/builds/484467650?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/hibana/25?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by JohnTitor** [comment]
Hmmm, CircleCIの方の結果を見てしまっている

**Pull request merged**
