### PR TITLE
Ignore branch `auto`

### LINKED ISSUE #26: Restrict tested branches on CircleCI
### Summary

こんな感じでCircleCIのステータスを見てmergeしてしまっている
https://github.com/student-kyushu/hibana/pull/22#issuecomment-457651480

CircleCIがテストするブランチを制限したい

### Expected behaviour

CircleCIはPRが投げられたときだけ走ってくれると良さそう
auto/masterブランチはTravis CIが担当する感じで

### Actual behaviour

CircleCIがauto/masterもテストしてしまい軽めのテストでmergeされてしまう

### PR DESCRIPTION
**Pull request by JohnTitor**
### Types of this PR

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation
- [x] Test
- [ ] Refactor

### Description

Fixes #26

### CODE REVIEW

**Comment by JohnTitor** [comment]
r+

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 51b2361fbe118aca693f4e63678746ced14e32e2 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 51b2361fbe118aca693f4e63678746ced14e32e2 has been merged into the auto branch cebe6d8179deaa6a747fad247a9ce4c44e0adf99

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/student-kyushu/hibana/builds/484491224?utm_source=github_status&utm_medium=notification)

**Pull request merged**
